# Generated by Django 3.0.3 on 2020-02-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200227_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (4, 'Used - Not Working'), (2, 'Used - Good'), (0, 'Brand New'), (3, 'Used - working')], default=4),
        ),
    ]
