# Generated by Django 3.0.3 on 2020-02-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200227_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (2, 'Used - Good'), (3, 'Used - working'), (0, 'Brand New'), (4, 'Used - Not Working')], default=4),
        ),
    ]
