# Generated by Django 3.0.3 on 2020-02-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200227_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - working'), (2, 'Used - Good'), (4, 'Used - Not Working'), (1, 'Used - Like New'), (0, 'Brand New')], default=4),
        ),
    ]
