# Generated by Django 3.0.3 on 2020-02-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200227_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Working'), (2, 'Used - Good'), (1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - working')], default=4),
        ),
    ]
