# Generated by Django 3.0.3 on 2020-02-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200227_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (0, 'Brand New'), (1, 'Used - Like New'), (3, 'Used - working'), (4, 'Used - Not Working')], default=4),
        ),
    ]
