# Generated by Django 3.0.5 on 2020-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200415_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Usable'), (1, 'Used - Like New'), (2, 'Used - Good'), (3, 'Used - Poor Condidtion'), (0, 'Brand New')], default=4),
        ),
    ]
