# Generated by Django 3.0.5 on 2020-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20200730_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - Poor Condidtion'), (1, 'Used - Like New'), (2, 'Used - Good'), (4, 'Used - Not Usable'), (0, 'Brand New')], default=4),
        ),
    ]
