# Generated by Django 3.0.5 on 2020-07-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_auto_20200730_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Usable'), (0, 'Brand New'), (2, 'Used - Good'), (3, 'Used - Poor Condidtion'), (1, 'Used - Like New')], default=4),
        ),
    ]
