# Generated by Django 3.0.5 on 2020-07-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_auto_20200730_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (0, 'Brand New'), (4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion'), (2, 'Used - Good')], default=4),
        ),
    ]
