# Generated by Django 3.0.5 on 2020-07-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_auto_20200730_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (2, 'Used - Good'), (0, 'Brand New'), (4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion')], default=4),
        ),
    ]
