# Generated by Django 3.1.3 on 2020-11-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_auto_20201125_0244'),
        ('posts', '0060_auto_20201127_0253'),
    ]

    operations = [
    ]
