# Generated by Django 3.0 on 2020-12-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0075_auto_20201203_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (4, 'Used - Not Usable'), (2, 'Used - Good'), (1, 'Used - Like New'), (3, 'Used - Poor Condidtion')], default=4),
        ),
    ]
