# Generated by Django 3.0 on 2020-12-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0078_auto_20201204_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion'), (0, 'Brand New'), (2, 'Used - Good')], default=4),
        ),
    ]
