# Generated by Django 3.0.3 on 2020-02-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation',
        ),
    ]
