# Generated by Django 3.0.3 on 2020-02-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userprofile_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
