# Generated by Django 3.0 on 2020-12-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20201203_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/media/images/no-image-available-icon-6.jpg', null=True, upload_to='images/profile_images'),
        ),
    ]
