# Generated by Django 3.0 on 2020-12-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
