# Generated by Django 3.1.3 on 2020-11-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20201127_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (0, 'Brand New'), (2, 'Used - Good'), (4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion')], default=4),
        ),
    ]
