# Generated by Django 3.0 on 2020-11-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20201127_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - Poor Condidtion'), (2, 'Used - Good'), (1, 'Used - Like New'), (4, 'Used - Not Usable'), (0, 'Brand New')], default=4),
        ),
    ]
