# Generated by Django 3.0 on 2020-12-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20201130_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - Poor Condidtion'), (2, 'Used - Good'), (4, 'Used - Not Usable')], default=4),
        ),
    ]
