# Generated by Django 3.0 on 2020-12-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_auto_20201203_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Usable'), (1, 'Used - Like New'), (3, 'Used - Poor Condidtion'), (0, 'Brand New'), (2, 'Used - Good')], default=4),
        ),
    ]
