# Generated by Django 3.0 on 2020-12-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_auto_20201204_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (3, 'Used - Poor Condidtion'), (4, 'Used - Not Usable'), (2, 'Used - Good'), (1, 'Used - Like New')], default=4),
        ),
    ]
