# Generated by Django 3.0 on 2020-12-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20201204_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (2, 'Used - Good'), (4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion'), (0, 'Brand New')], default=4),
        ),
    ]
